Schema.Dispatch=new SimpleSchema
  note:
    type:String
    optional:true
    defaultValue:"Dispatched"
    autoform:
      afFieldInput:
        rows:5
  schedule:
    type:String
    optional:true
    autoform:
      type:"hidden"
      label:false
  photos:
    type:String
    optional:true
    autoform:
      type:'uploadCare'
      options:
        classStyle:'uploader-green-button'