Schema.Message=new SimpleSchema
  isNew:
    type:Boolean
    defaultValue:true
    autoform:
      type:'hidden'
      label:false
  parent:
    type:String
    optional:true
    autoform:
      type:'hidden'
      label:false
  message:
    type:String
    autoform:
      label:false
      placeholder:"schemaLabel"
      rows:3
  documentId:
    type:String
    autoform:
      type:'hidden'
      label:false
  collectionName:
    type:String
    autoform:
      type:'hidden'
      label:false
  audience:
    type:[String]
    optional:true
    autoform:
      type:'hidden'
      label:false
