Schema.Rating=new SimpleSchema
  accuracy:
    type:Number
    defaultValue:0
    autoform:
      type:'rating'
      description:TEXT_ACCURACY
      mutable:true
      size:'lg'
  performance:
    type:Number
    defaultValue:0
    autoform:
      type:'rating'
      description:TEXT_PERFORMANCE
      mutable:true
      size:'lg'
      hide:()-> not RP_permissions.hasPermissions('canRatePerformance')
      label:()-> not RP_permissions.hasPermissions('canRatePerformance')
  timeliness:
    type:Number
    defaultValue:0
    autoform:
      type:'rating'
      description:TEXT_TIMELINESS
      mutable:true
      size:'lg'
  delivery:
    type:Number
    defaultValue:0
    autoform:
      type:'rating'
      description:TEXT_DELIVERY
      mutable:true
      size:'lg'
      hide:()-> not RP_permissions.hasPermissions('canRateDelivery')
      label:()-> not RP_permissions.hasPermissions('canRateDelivery')
  average:
    type:Number
    optional:true
    decimal:true
    defaultValue:0
    autoform:
      label:false
      type:'hidden'
  comments:
    type:String
    optional:true
    autoform:
      rows:6
  schedule:
    type:String
    autoform:
      label:false
      type:'hidden'
  owner:
    type:String
    autoform:
      label:false
      type:'hidden'
  child:
    type:String
    optional:true
    autoform:
      label:false
      type:'hidden'
