@STATE_MATCHED='matched'
@STATE_UNMATCHED='unmatched'
@STATE_NEW='new'
@STATE_BOOKED='accepted'
@STATE_ASSIGNED='booked'
@STATE_CANCELLED='cancelled'
@STATE_SUCCESS='delivered'
@STATE_LATE='late'
@STATE_ISSUE='issue'
@STATE_DISPATCH='dispatched'
@STATE_BIDDED='bidded'

@ROLE_DRIVER='driver'
@ROLE_SHIPPER='shipper'
@ROLE_TRUCKER='trucker'
@ROLE_CLERK='clerk'

@COLLECTION_BID='Bids'
@COLLECTION_REQUEST='Schedules'
@COLLECTION_MESSAGE='Messages'
@COLLECTION_ACTIVITY='Activities'